version: "3.9"

services:
  #   postgres:
  #     image: postgres:14.19
  #     platform: linux/amd64
  #     container_name: rust_in_motion_postgres
  #     restart: always
  #     environment:
  #       POSTGRES_USER: wangweichun
  #       POSTGRES_PASSWORD: WW_33_cc
  #       POSTGRES_DB: rust_in_motion
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  #     # ports:
  #     #   - "5432:5432"
  #     networks:
  #       - blog-network

  leptos:
    image: rust_in_motion:1.0.1 # 指定镜像版本
    build: .
    platform: linux/amd64
    container_name: rust_in_motion_app
    restart: always
    # depends_on:
    #   - postgres
    # env_file:
    #   - .env
    environment:
      DATABASE_URL: postgres://wangweichun:WW_33_cc@postgres:5432/rust_in_motion
    ports:
      - "3000:3000"
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
