//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "project")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub project_name: String,
    pub introduction: String,
    pub tags: Vec<String>,
    pub cover_image_url: Option<String>,
    pub type_id: i32,
    pub create_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::project_type::Entity",
        from = "Column::TypeId",
        to = "super::project_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProjectType,
}

impl Related<super::project_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
